ARG WEB_BUILDER=internal

FROM --platform=$BUILDPLATFORM node:22 AS web-builder-internal

COPY web/package.json /web/package.json
COPY web/shared/ /web/shared/
COPY web/frpc/ /web/frpc/
WORKDIR /web
RUN npm install
WORKDIR /web/frpc
RUN npm run build

FROM scratch AS web-builder-external

FROM --platform=$BUILDPLATFORM golang:1.25 AS building-internal
WORKDIR /building
COPY . /building
COPY --from=web-builder-internal /web/frpc/dist /building/web/frpc/dist

FROM --platform=$BUILDPLATFORM golang:1.25 AS building-external
WORKDIR /building
COPY . /building

ARG WEB_BUILDER=internal
FROM building-${WEB_BUILDER} AS building-base

ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT

RUN env CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} GOAMD64=${TARGETVARIANT} \
    go build -trimpath -ldflags "-s -w" -tags frpc -o bin/frpc ./cmd/frpc

FROM alpine:3

RUN apk add --no-cache tzdata

COPY --from=building-base /building/bin/frpc /usr/bin/frpc

ENTRYPOINT ["/usr/bin/frpc"]
