FROM --platform=$BUILDPLATFORM golang:1.25 AS building

ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT
ARG GOPROXY=https://goproxy.cn,direct

ENV GOPROXY=${GOPROXY}

COPY . /building
WORKDIR /building

RUN env CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} GOAMD64=${TARGETVARIANT} \
    go build -trimpath -ldflags "-s -w" -tags frps -o bin/frps ./cmd/frps

FROM alpine:3

RUN apk add --no-cache tzdata

COPY --from=building /building/bin/frps /usr/bin/frps

ENTRYPOINT ["/usr/bin/frps"]
