FROM --platform=$BUILDPLATFORM golang:1.25 AS building

ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT
ARG GOPROXY=https://goproxy.cn,direct

ENV GOPROXY=${GOPROXY}

COPY . /building
WORKDIR /building

RUN env CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} GOAMD64=${TARGETVARIANT} \
    go build -trimpath -ldflags "-s -w" -tags frpc -o bin/frpc ./cmd/frpc

FROM alpine:3

RUN apk add --no-cache tzdata

COPY --from=building /building/bin/frpc /usr/bin/frpc

ENTRYPOINT ["/usr/bin/frpc"]
